language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
  - rvmsudo gem install sass
  - gem environment

  - export scss=`gem environment | grep '\- INSTALLATION DIRECTORY:' | sed 's/\- INSTALLATION DIRECTORY: //'`/gems/sass*/bin/scss
  - echo 'scss' $scss
